export const SIGNUP='SIGNUP';
export const SIGNUP_ERROR='SIGNUP_ERROR';
export const SIGNUP_REQUEST='SIGNUP_REQUEST';

export const SIGNIN ='SIGNIN';
export const SIGNIN_ERROR='SIGNIN_ERROR';
export const SIGNIN_REQUEST='SIGNIN_REQUEST';


export const GET_SECTION="GET_SECTION";
export const GET_SECTION_ERROR="GET_SECTION_ERROR"

export const GET_PLANS ="GET_PLANS";
export const GET_PLANS_ERROR="GET_PLANS_ERROR";

export const GET_PLANS_REQUEST="GET_PLANS_REQUEST";

export const GET_ALL_PLANS="GET_ALL_PLANS";
export const GET_ALL_PLANS_REQUEST="GET_ALL_PLANS_REQUEST";
export const GET_ALL_PLANS_ERROR="GET_ALL_PLANS_ERROR";

export const GET_SINGLE_PLAN="GET_SINGLE_PLAN";
export const GET_SINGLE_PLAN_ERROR="GET_SINGLE_PLAN_ERROR";


export const GET_ALL_PLANS_PROJECTION="GET_ALL_PLANS_PROJECTION";
export const GET_ALL_PLANS_PROJECTION_ERROR="GET_ALL_PLANS_PROJECTION_ERROR";

export const GET_BANKS_REQUEST="GET_BANKS_REQUEST";
export const GET_ALL_BANKS="GET_ALL_BANKS";
export const GET_ALL_BANKS_ERROR="GET_ALL_BANKS_ERROR";

export const GET_RATES="GET_RATES";
export const GET_RATES_ERROR="GET_RATES_ERROR";
export const GET_ALL_RATES_REQUEST="GET_ALL_RATES_REQUEST";

export const GET_QUOTE="GET_QUOTE";
export const GET_QUOTE_ERROR="GET_QUOTE_ERROR";
export const GET_QUOTE_REQUEST="GET_QUOTE_REQUEST="